// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxskmpiosuszprycprax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4c2ttcGlvc3VzenByeWNwcmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTY4OTUsImV4cCI6MjA2OTQ3Mjg5NX0.8xQs2sR_ZwjDjWGe8bJUmx8KR2x25yNOJYODhqHegmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});